sudo: true
dist: xenial

language: cpp
compiler: clang
addons:
  apt:
    packages:
    - libssl-dev
    - ninja
    - openssl
    - zlib1g-dev
    - gperf
    - liblua5.2-dev
    - rapidjson-dev
    - lua5.2
    
script:
- ./compile.sh
