sudo: true
dist: xenial

language: cpp
compiler: clang
addons:
  apt:
    update: true
    packages:
    - libssl-dev
    - ninja
    - openssl
    - zlib1g-dev
    - gperf
    - liblua5.4-dev
    - rapidjson-dev
    - lua5.4
    
script:
- ./compile.sh
