sudo: true
dist: xenial

language: cpp

before_install:
  - sudo apt-get -y update
  - sudo apt-get install -y build-essential clang libssl-dev ninja openssl zlib1g-dev cmake gperf liblua5.2-dev rapidjson-dev lua5.2

script:
- git clone https://github.com/giuseppeM99/tdlua
- cd tdlua
- ./compile.sh
